title: Stepan Balashov
email: stbalashovl@gmail.com
description: >- 
  Stepan Balashov CV
baseurl: "" 
url: "https://stbalashov.com" 
github_username:  StBalashov

theme: minima

collections: 
  cv:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pdf

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
